#!/usr/bin/env python3

import sys

if sys.version_info[0] < 3 or sys.version_info[1] < 2:
    print("You need at least Python 3.2 to run FS-UAE Launcher")
    sys.exit(1)

# Workaround to make import typing work without having it on the default
# python path (would confuse mypy).

import fstd.typing
sys.modules["typing"] = fstd.typing

import os
import socket
from fsgs.FSGSDirectories import FSGSDirectories
from fsbc.init import initialize_application

FSGSDirectories.initialize()
socket.setdefaulttimeout(30.0)
initialize_application("fs-uae-arcade", version="2.6.1")
os.environ["SDL_VIDEO_MAC_FULLSCREEN_SPACES"] = "0"

try:
    import game_center.main
    game_center.main.main()
    print("main returned")

finally:
    from fsbc.Application import Application
    application = Application.instance()
    if application:
        print("calling Application stop")
        Application.get().stop()

    from fsbc.signal import Signal
    print("sending quit signal")
    Signal("quit").notify()
