#!/usr/bin/env python3

import sys

if sys.version_info[0] < 3 or sys.version_info[1] < 2:
    print("You need at least Python 3.2 to run FS-UAE Launcher")
    sys.exit(1)

# Workaround to make import typing work without having it on the default
# python path (would confuse mypy).

import fstd.typing
sys.modules["typing"] = fstd.typing

import os
import socket
from fsgs.FSGSDirectories import FSGSDirectories
from fsbc.init import initialize_application


socket.setdefaulttimeout(30.0)
initialize_application("fs-uae-arcade", version="2.8.3")
os.environ["SDL_VIDEO_MAC_FULLSCREEN_SPACES"] = "0"

try:
    import arcade.arcade_main
    arcade.arcade_main.main()
    print("main returned")

finally:
    from fsbc.application import Application
    application = Application.instance()
    if application:
        print("calling Application stop")
        Application.get().stop()

    from fsbc.signal import Signal
    print("sending quit signal")
    Signal("quit").notify()

# Dummy imports for cx_Freeze
sys.exit(0)
import pkg_resources._vendor.packaging.requirements
import pkg_resources._vendor.packaging.specifiers
import pkg_resources._vendor.packaging.version
import pkg_resources._vendor.pyparsing
import pkg_resources._vendor.six
